### ISSUE TITLE
Lookup field update error

### ISSUE THREAD

**Issue by 990706TJGU** [kintone/js-sdk#767] opened 2021-03-18 16:34 UTC
Error: [520] [GAIA_LO04] A value 129 in the field xxx does not exist in the datasource app for lookup, or you do not have permission to view the app or the field.

Hi, I keep getting this error message when updating a lookup field of an app, there is nothing wrong when I update other types of fields.
Can you tell me how to solve this problem? 
Thanks a lot.

**Comment by zaki-yama** [comment] 2021-03-19 01:10
@990706TJGU 
Thanks for reporting!
To investigate the cause, would you give us more information?
Please tell us about the package version, environment, etc. by following the issue template.
(You don't have to close this issue, just update the description of it)

```
<!-- Thank you for reporting a bug! -->

## Target Package

<!-- Which package do you want to report a bug for? -->

- @kintone/\*\*\* 0.0.0

## Environment

<!-- What environment did you test? -->

- Operating System:
- Browser:
- Node.js version:

## Current Behavior

<!-- What is the current behavior you saw?  -->


## Expected Behavior

<!-- What is the behavior you expected?  -->
```

Also, we'd like to know which authentication method you use.
https://github.com/kintone/js-sdk/tree/master/packages/rest-api-client#authentication

**Comment by zaki-yama** [comment] 2021-06-15 05:12
@990706TJGU 
I'll close this issue because it hasn't had any updates for a few months.
But please feel free to reply if you still have any problems.

**Closed by zaki-yama** 2021-06-15 05:12 UTC
Labels: bug, pkg: rest-api-client
